config/routes.rb
Rails.application.routes.draw do

  # home page
  root 'sessions#home'

  # create an account route
  get '/signup' => "users#new"
  post '/signup' => "users#create"

  # existing user login route
  get '/signin' => "sessions#new"
  post '/signin' => "sessions#create"

  # callback route for google oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'

  # logout route
  delete '/logout' => "sessions#destroy"

  delete '/task/:id' => "tasks#destroy"

  delete '/suggestions/:id' => "suggestions#destroy"

  resources :friendships
  
  resources :suggestions
  resources :tasks do # custom route to handle task :id
    resources :suggestions, only: [:new, :create, :index, :edit]
    get '/suggestions/random', to: 'suggestions#show', as: 'winner'
  end
  resources :users do
    resources :tasks, only: [:new, :create, :index, :edit]
  end
end

# random route that renders show template, i.e task/:id/suggestions/random, -> create custom route to handle task :id

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    has_many :suggestions
    has_many :users, through: :suggestions
    validates :content, presence: true
    
    # scope :most_suggestions, -> 
    # {left_join(:suggestions) // joins suggestions & tasks tables (left join will give ALL tasks where joins will give only tasks that have suggestions)
    # .group('task.id') // groups together by task.id (otherwise you might have Task id "1" 3 times)
    # .order('count // orders each group by count
    # (tasks.id) // tells what to count (if just id, unclear whether tasks or suggestion id)
    # desc')} // starts w/ highest to lowest
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_task_author, only: [:edit, :update, :destroy]
    
    def index
        if params[:user_id] # checks if post ID & id exists are true
            @user = User.find_by(id: params[:user_id])
            @tasks = @user.tasks
        else
            @tasks = Task.all
        end
        
    end
    
    def new
        @task = Task.new
    end

    def create
        @task = current_user.tasks.build(task_params)
        if @task.save
            flash.notice = "Successfully created new task."
            redirect_to tasks_path
        else
            render :new
        end
    end

    def show
        @task = Task.find_by(id: params[:id])
    end

    def edit
    end

    def update
        if @task.update(task_params)
            flash.notice = "Successfully updated new task."
            redirect_to task_path(@task)
        else
            render :edit
        end
    end

    def destroy
        @task.suggestions.each do |s|
            s.destroy
        end
        @task.destroy
        flash[:notice] = "Task deleted."
        redirect_to tasks_path
    end

    private

    def task_params
        params.require(:task).permit(:content)
    end


    def set_task
        @task = Task.find_by(id: params[:id])
        if !@task || @task == nil
            flash[:alert] = "Task was not found."
            redirect_to tasks_path
        end
    end

    def redirect_if_not_task_author
        if @task.user != current_user
            flash[:alert] = "You are not authorized to make changes to this task."
            redirect_to task_path
        end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
    def display_index_header
    end
end

app/views/tasks/_tasks.html.erb
<%= form_for(@task) do |f| %>

    <%= f.label :content, "Task:" %>
    <%= f.text_area :content %>

    <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<div id="main">
    <h3> Edit Task </h3>

    <%= render partial: "layouts/errors", locals: {object: @task} %>

    <div id="frm">
        <%= render partial: "tasks" %>
    </div>
</div>

app/views/tasks/index.html.erb
<h1>All tasks</h1>
<hr>
<% if @tasks.empty? %>
    <%= "#{@user.firstname} has not created any tasks yet." %>
<% else %>
    <table>
        <tr>
            <th> Task: </th>
            <th> Created by: </th>
            <th> Link to task: </th>
        </tr>
    
        <% @tasks.each do |task| %>
            <tr>
                <td> <%= task.content %> </td>
                <td> <%= task.user.firstname %> </td>
                <td> <%= link_to "See This Task", task_path(task)%> </td>
            </tr>
        <% end %>
    </table>
<% end %>


app/views/tasks/new.html.erb
<div id="main">
    
    <h3> Create a new task </h3>
    <br>
    <%= render partial: "layouts/errors", locals: {object: @task} %>
    <div id="frm">
        <%= render partial: "tasks" %>
    </div>
</div>

app/views/tasks/show.html.erb
<div id="main">
    <h1> <%= @task.content %> </h1>
    <h4> Created by: <%= @task.user.firstname %> </h4>
    <br>
    <hr>
    <br>
    <% if @task.suggestions.empty? %>
        <%= "No suggestions yet for '#{@task.content}'." %>
    <% else %>
        <% @task.suggestions.each do |suggestion| %>
            <div class="card text-center" style="width: 25%; height: 50%; vertical-align: middle;">
                <h5 class="card-header">Suggestion</h5>
                    <div class="card-body">
                        <h5 class="card-title"><%= suggestion.content %></h5>
                        <p class="card-text">Suggested by: <strong> <%= suggestion.user.firstname %> </strong></p>
                        <% if suggestion.user == current_user %>
                            <%= link_to "edit", edit_suggestion_path(suggestion) %>
                            <%= link_to "delete", suggestion_path(suggestion), method: :delete %>
                        <% end %>
                    </div>
                </div>
            <br>
        <% end %>
    <% end %> 

    <br>
    <% if current_user || current_user.friends.exists?(@task.user.id) %>
        <%= link_to "Add a new suggestion", new_task_suggestion_path(@task) %> 
    <% else %>
        You must follow this user to add a suggestion.
    <% end %>
    <br>
    <% if @task.user == current_user %>
        <%= link_to "Randomize suggestions", task_winner_path(@task) %> 
    <% end %>
</div>