config/routes.rb
Rails.application.routes.draw do

  # home page
  root 'sessions#home'

  # create an account route
  get '/signup' => "users#new"
  post '/signup' => "users#create"

  # existing user login route
  get '/signin' => "sessions#new"
  post '/signin' => "sessions#create"

  # callback route for google oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'

  # logout route
  delete '/logout' => "sessions#destroy"

  delete '/task/:id' => "tasks#destroy"

  delete '/suggestions/:id' => "suggestions#destroy"

  resources :friendships
  
  resources :suggestions
  resources :tasks do # custom route to handle task :id
    resources :suggestions, only: [:new, :create, :index, :edit]
    get '/suggestions/random', to: 'suggestions#show', as: 'winner'
  end
  resources :users do
    resources :tasks, only: [:new, :create, :index, :edit]
  end
end

# random route that renders show template, i.e task/:id/suggestions/random, -> create custom route to handle task :id

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, uniqueness: true
    validates :email, :password, presence: true
    has_many :tasks
    has_many :suggestions
    has_many :suggestions_added, through: :tasks, source: :task # connects user to task through suggestions join table (has_many :suggestions through :comments)
    has_many :friendships
    has_many :friends, :through => :friendships
    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id" # other side of friendship association
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user # so that it will fetch information from user (owner of friendship)

    scope :alpha, -> { order(:firstname) }

    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
            user.firstname = auth["info"]["first_name"]
            user.lastname = auth["info"]["lastname"]
            user.password = SecureRandom.hex
        end
    end

    def self.search(params)
        where("LOWER(firstname) LIKE :name OR LOWER(lastname) LIKE :name", name: "%#{params}%") # selects * from DB where firstname = params, converts all firstname column to lowercase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.alpha
        if params[:q] && !params[:q].empty? # looks at URL for query
            @users = @users.search(params[:q].downcase) # calls on search method in user model & makes search case insensitive
        end
    end
    # create an account page
    def new
        @user = User.new
    end

    # creates new user or redirects
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by(id: params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:firstname, :lastname, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
User List

<%= form_tag("/users", method: "get") do %>
  <%= label_tag(:q, "Search by First Name:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<% for user in @users %>
  <% if user.id != current_user.id && !current_user.friends.exists?(user.id) %>
    <p>
      <%= user.firstname %>
      <%= user.lastname %>
      <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
    </p>
  <% end %>
<% end %>

app/views/users/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @user} %>

<div id="main">
    <h1>Sign Up</h1>
    <div id="frm">
        <%= form_for(@user) do |f| %>
            <%= f.label :firstname, "First Name" %>
            <%= f.text_field :firstname %>

            <%= f.label :lastname, "Last Name" %>
            <%= f.text_field :lastname %>

            <%= f.label :email %>
            <%= f.text_field :email %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.submit "Create Account"%>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div id="main">
    <% if @user.tasks.empty? %>
        No tasks yet. Create a new task <%= link_to "here", new_task_path %>
    <% else %>
        <br>
        <br>
        <h3><%=@user.firstname%>'s tasks: </h3>
        <br>
        <% @user.tasks.each do |task| %>
            <%= link_to "#{task.content}", task_path(task) %>
            <% if @user == current_user %>
                <div id="user_hp_button"> <%= button_to "edit", edit_task_path(task), :method => :get %> </div>
                <div id="user_hp_button"> <%= button_to "delete", task_path(task), method: :delete %> </div>
            <% end %>
            <br>
        <% end %>
        <br>
    <% end %>
</div>
