config/routes.rb
Rails.application.routes.draw do

  # home page
  root 'sessions#home'

  # create an account route
  get '/signup' => "users#new"
  post '/signup' => "users#create"

  # existing user login route
  get '/signin' => "sessions#new"
  post '/signin' => "sessions#create"

  # callback route for google oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'

  # logout route
  delete '/logout' => "sessions#destroy"

  delete '/task/:id' => "tasks#destroy"

  delete '/suggestions/:id' => "suggestions#destroy"

  resources :friendships
  
  resources :suggestions
  resources :tasks do # custom route to handle task :id
    resources :suggestions, only: [:new, :create, :index, :edit]
    get '/suggestions/random', to: 'suggestions#show', as: 'winner'
  end
  resources :users do
    resources :tasks, only: [:new, :create, :index, :edit]
  end
end

# random route that renders show template, i.e task/:id/suggestions/random, -> create custom route to handle task :id

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, :class_name => "User" # uses User model for association since friend model does not exist
   

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :redirect_if_not_logged_in
    
    def create
        @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
        if @friendship.save
            flash[:notice] = "Added friend."
            redirect_to current_user
        else
            flash[:error] = "Unable to add friend."
            redirect_to user_path(@user)
        end
    end
  
    def destroy
        @friendship = current_user.friendships.find(params[:id]) #only current user's friendships
        @friendship.destroy
        flash[:notice] = "Removed friendship."
        redirect_to current_user
    end

    def index
    end
end

app/views/friendships/index.html.erb
<h1> Your Friends </h1>

<h2>Users you follow:</h2>
<ul>
  <% for friendship in current_user.friendships %>
      <li>
        <%= link_to "#{friendship.friend.firstname}", user_tasks_path(friendship.friend.id) %>
        (<%= link_to "remove", friendship, :method => :delete %>)
      </li>
  <% end %>
</ul>

<p><%= link_to "Find Friends", users_path %></p>

<h2>Users who follow you:</h2>
<ul>
  <% for user in current_user.inverse_friends %>
    <li><%=h user.firstname %></li>
  <% end %>
</ul>