config/routes.rb
Rails.application.routes.draw do

  # home page
  root 'sessions#home'

  # create an account route
  get '/signup' => "users#new"
  post '/signup' => "users#create"

  # existing user login route
  get '/signin' => "sessions#new"
  post '/signin' => "sessions#create"

  # callback route for google oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'

  # logout route
  delete '/logout' => "sessions#destroy"

  delete '/task/:id' => "tasks#destroy"

  delete '/suggestions/:id' => "suggestions#destroy"

  resources :friendships
  
  resources :suggestions
  resources :tasks do # custom route to handle task :id
    resources :suggestions, only: [:new, :create, :index, :edit]
    get '/suggestions/random', to: 'suggestions#show', as: 'winner'
  end
  resources :users do
    resources :tasks, only: [:new, :create, :index, :edit]
  end
end

# random route that renders show template, i.e task/:id/suggestions/random, -> create custom route to handle task :id

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
        <% object.errors.full_messages.each do |message| %>
            <%= message %>
            <br>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Decider</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Spirax&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    
    <div id="navbar">
        <% if logged_in? %>
        <ul>
          <li><%= link_to "Home Page", user_path(current_user) %> </li>
          <li><%= link_to "Add a task", new_task_path %> </li>
          <li><%= link_to "All tasks", tasks_path %> </li>
          <li><%= link_to "Your Friends", friendships_path %> </li>
          <li><%= link_to "Logout", logout_path, method: "delete" %> </li>
        </ul>
      <% end %>
    </div>

    

    <%= yield %>
  </body>
  <footer>
      This page was created by Carrie Mathieu.
  </footer
</html>